id: I0352EF39
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.849307
last_modified: 2023-02-08 15:15:38.849414
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: en
bases:
  CE78:
    base_file: CE78.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
